import { defaultProps } from "./defaultProps";

export const schema = {
  title: "Banner de Benefícios",
  description: "Custom component BenefitsBanner",
  type: "object",
  properties: {
    discount: {
      title: "Percentual de desconto",
      description:
        "Informe o percentual de desconto para exibir no banner",
      type: "string",
      default: defaultProps.discount,
    },
    installments: {
      title: "Número de parcelas",
      description: "Parcelamento sem juros",
      type: "string",
      default: defaultProps.installments,
      enum: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
      ],
      enumNames: [
        "1x",
        "2x",
        "3x",
        "4x",
        "5x",
        "6x",
        "7x",
        "8x",
        "9x",
        "10x",
        "11x",
        "12x",
      ],
    },
    icon: {
      title: "Ícone PIX",
      description: "Ícone PIX para pagamento via PIX",
      type: "string",
      default: defaultProps.installments,
      widget: {
        "ui:widget": "image-uploader",
      },
    },
    textColor: {
      title: "Cor do texto",
      description: "Cor do texto",
      type: "string",
      default: defaultProps.installments,
      widget: {
        "ui:widget": "color",
      },
    },
    date: {
      title: "Data de vencimento",
      description: "Data de vencimento",
      type: "string",
      widget: {
        "ui:widget": "date",
      },
    },
    testSelect: {
      title: "Teste select",
      description: "Teste select",
      type: "string",
      enum: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
      ],
    },
    testBoolean: {
      title: "Teste boolean",
      description: "Teste boolean",
      type: "boolean",
      default: true,
    },
    testRadio: {
      title: "Teste radio",
      description: "Teste radio",
      type: "string",
      enum: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
      ],
      enumNames: [
        "1x",
        "2x",
        "3x",
        "4x",
        "5x",
        "6x",
        "7x",
        "8x",
        "9x",
        "10x",
        "11x",
        "12x",
      ],
      widget: {
        "ui:widget": "radio",
      },
    },
    richtext:{
        title: "Texto do Componente",
        description: "Exemplo de Richtext",
        type: "string",
        defaultProps: defaultProps.richtext,
        widget: {
          "ui:widget": "textarea",
        },
    }
  },
};
